import { useEffect, useMemo, useRef, useState } from 'react';
import ClassicPortfolio from './App.jsx';
import GraphScene from './GraphScene.jsx';
import { categories, makeGraph, graphView, scopes } from './graph-data.js';
import { details, profile, skills, certifications } from './project-details.js';
import { links } from './content.js';
import './developer.css';
export default function Portfolio() { return new URLSearchParams(location.search).get('view') === 'classic' ? <ClassicPortfolio /> : <DeveloperPortfolio />; }
function DeveloperPortfolio() {
  const { nodes, edges } = useMemo(() => makeGraph('en'), []);
  const readNode = () => nodes.some(n => n.id === location.hash.slice(1)) ? location.hash.slice(1) : 'dogukan';
  const [selected, setSelected] = useState(readNode);
  const [filter, setFilter] = useState('all');
  const [focus, setFocus] = useState('');
  const [view, setView] = useState(() => innerWidth < 600 ? 'list' : 'graph');
  const [zoom, setZoom] = useState(1);
  const [resetKey, setResetKey] = useState(0);
  const [rotating, setRotating] = useState(() => !matchMedia('(prefers-reduced-motion: reduce)').matches);
  const previous = useRef(selected);
  const node = nodes.find(n => n.id === selected) || nodes[0];
  const expanded = selected !== 'dogukan', project = details[node.detailKey];
  const related = edges.filter(e => e.from === selected || e.to === selected).map(e => ({ ...nodes.find(n => n.id === (e.from === selected ? e.to : e.from)), relation: e.label })).filter(n => n.id !== 'dogukan');
  const visibleGraph = useMemo(() => graphView(nodes, edges, filter, focus), [nodes, edges, filter, focus]);
  const items = visibleGraph.nodes.filter(n => n.kind !== 'skill' && n.kind !== 'person');
  function chooseFilter(id) { setFilter(id); setFocus(scopes[id]?.[0] || ''); setResetKey(k => k + 1); setZoom(1);  }
  function scrollToExplorer() {
    document.getElementById('explorer-heading')?.focus({ preventScroll: true });
    document.getElementById('work')?.scrollIntoView({ behavior: 'instant', block: 'start' });
  }
  function scrollToDetails() {
    document.getElementById('project-heading')?.focus({ preventScroll: true });
    document.getElementById('project-detail')?.scrollIntoView({ behavior: 'instant', block: 'start' });
  }
  function change(id) {
    if (id === selected) { id === 'dogukan' ? scrollToExplorer() : scrollToDetails(); return; }
    history.pushState(null, '', id === 'dogukan' ? '#work' : `#${id}`);
    setSelected(id);
  }
  useEffect(() => { const update = () => { const hash = location.hash.slice(1); if (nodes.some(n => n.id === hash) || hash === 'work' || !hash) { setSelected(readNode());  } }; window.addEventListener('popstate', update); window.addEventListener('hashchange', update); return () => { window.removeEventListener('popstate', update); window.removeEventListener('hashchange', update); }; }, [nodes]);
  useEffect(() => {
    document.title = `${expanded ? node.title : 'Software Engineer'} — Dogukan Demir`;
    if (previous.current !== selected || expanded) {
      expanded ? scrollToDetails() : scrollToExplorer();
    }
    previous.current = selected;
  }, [selected]);
  function reset() { setZoom(1); setResetKey(k => k + 1); setFilter('all'); setFocus('');  }
  return <div className="dev-site"><a className="dev-skip" href="#work">Skip to projects</a>
    <header className="dev-header"><a className="dev-brand" href="#top"><span className="name-brand">Dogukan Demir<small>SOFTWARE ENGINEER</small></span></a><nav aria-label="Main navigation"><a href="#work" onClick={e => { e.preventDefault(); scrollToExplorer(); }}>Work</a><a href="#background">Background</a><a href={links.github} target="_blank" rel="noopener noreferrer">GitHub ↗</a></nav></header>
    <main><section id="top" className="dev-hero"><div className="hero-main"><p className="dev-eyebrow"><span className="status-dot" /> BASED IN GERMANY · BUILDING ACROSS DISCIPLINES</p><h1>Hi, I’m Dogukan.<br />I build the systems<br /><span>behind the experience.</span></h1><p className="hero-summary">{profile.summary}</p><div className="hero-socials" aria-label="Social profiles">{[['github','GitHub'],['linkedin','LinkedIn'],['youtube','YouTube'],['email','Email']].map(([id,label])=><a key={id} href={links[id]} target={id==='email'?undefined:'_blank'} rel={id==='email'?undefined:'noopener noreferrer'}><span className="social-icon" aria-hidden="true">{id==='github'?'⌘':id==='linkedin'?'in':id==='youtube'?'▷':'@'}</span>{label}<span aria-hidden="true">↗</span></a>)}</div><div className="hero-stack">Go <i>/</i> C# & .NET <i>/</i> AWS & Azure <i>/</i> Unity</div></div><div className="hero-profile"><div className="profile-image"><img src="/images/me.jpeg" alt="Dogukan Demir" /></div></div></section>
    <section id="work" className={`dev-work ${expanded ? 'is-expanded' : ''}`} aria-label="Portfolio explorer"><div className="explorer-view"><div className="work-heading"><div><p className="dev-eyebrow">01 / SELECTED WORK</p><h2 id="explorer-heading" tabIndex={-1}>Different projects. Shared foundations.</h2><p>Explore how my work connects. Select any project to read the full story below.</p></div><div className="view-tabs" role="group" aria-label="Explorer view"><button aria-pressed={view === 'graph'} onClick={() => setView('graph')}>Graph</button><button aria-pressed={view === 'list'} onClick={() => setView('list')}>List</button></div></div>
    <div className="explorer-shell"><div className="graph-toolbar"><div className="graph-filters" role="group" aria-label="Filter projects">{[['all','All work'], ...Object.entries(categories).map(([id,c]) => [id,c.label])].map(([id,label]) => <button key={id} aria-pressed={id === filter} onClick={() => chooseFilter(id)}><span style={{ background: categories[id]?.color }} />{label}</button>)}</div><span className="graph-total">{items.length} ENTRIES</span></div>
    {filter !== 'all' && <div className="scope-tabs" role="group" aria-label="Choose organization">{scopes[filter].map(id=><button key={id} aria-pressed={focus===id} onClick={()=>{setFocus(id);setResetKey(k=>k+1);}}>{nodes.find(n=>n.id===id).title}</button>)}</div>}{view === 'graph' ? <div className="dev-graph-stage"><span className="graph-corner">INTERACTIVE WORK GRAPH <span> / 3D</span></span><GraphScene nodes={visibleGraph.nodes} edges={visibleGraph.edges} selected="dogukan" onSelect={id => { if (id !== 'dogukan') change(id); else document.getElementById('top')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}); }} filter={filter} resetKey={resetKey} zoom={zoom} rotating={rotating} /><span className="graph-key">Organization → project <span>{filter === 'all' ? 'Tools appear in focused views' : 'Project → technology'}</span></span></div> : <div className="dev-project-list">{items.map((n,i) => <button key={n.id} onClick={() => change(n.id)}><span className="list-index">{String(i+1).padStart(2,'0')}</span><span><small>{categories[n.category].label}</small><strong>{n.title}</strong><span>{details[n.id]?.subtitle || n.short}</span></span><span className="list-arrow">↗</span></button>)}</div>}
    <div className="graph-bottom"><p>{view === 'graph' ? 'Continuous slow orbit · Drag to explore · Pause anytime' : 'Select a project for its context, contributions, and outcomes.'}</p><div className="graph-controls">{view === 'graph' && <><button aria-label="Zoom out" disabled={zoom <= .7} onClick={() => setZoom(v=>Math.max(.7,v-.1))}>−</button><button aria-label="Zoom in" disabled={zoom >= 1.3} onClick={() => setZoom(v=>Math.min(1.3,v+.1))}>+</button><button aria-label={rotating ? 'Pause rotation' : 'Rotate graph'} aria-pressed={rotating} onClick={()=>setRotating(v=>!v)}>{rotating ? 'Ⅱ Pause' : '▷ Rotate'}</button></>}<button className="reset-button" onClick={reset}>↺ Reset view</button></div></div></div><p className="explorer-note">Prefer a straight path? Switch to List. Project details open below the explorer.</p></div>{expanded && <article id="project-detail" className="project-page" aria-labelledby="project-heading" key={selected}>
    <div className="project-nav"><button onClick={scrollToExplorer}>← Back to {view === 'graph' ? 'graph' : 'projects'}</button><span>WORK / {node.kind === 'skill' ? 'SHARED TECHNOLOGY' : categories[node.category]?.label.toUpperCase()}</span><button className="close-details" onClick={()=>change('dogukan')}>Close details ×</button></div><div className="project-title"><div><p className="dev-eyebrow">{project?.role || 'A CONNECTION ACROSS PROJECTS'}</p><h2 id="project-heading" tabIndex={-1}>{node.title}</h2><p>{project?.subtitle || node.body}</p></div>{node.href && <a className="dev-primary" href={node.href} target="_blank" rel="noopener noreferrer">{node.video ? 'View on Steam' : 'View toolkit'} ↗</a>}</div>{project && <div className="project-meta"><span>{project.period}</span><span>{project.place}</span></div>}
    {node.video && <figure className="project-video"><video controls playsInline preload="metadata" poster="/images/dead-inside-trailer.png" aria-label="Dead Inside — game trailer"><source src="/videos/Dead%20Inside.mp4" type="video/mp4" /><a href="/videos/Dead%20Inside.mp4">Download the trailer</a></video><figcaption><span>DEAD INSIDE / OFFICIAL GAME TRAILER</span><span>UNITY · C# · RELEASED ON STEAM</span></figcaption></figure>}
    {project?.metrics && <div className="project-metrics">{project.metrics.map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>}
    <div className="project-body"><aside className="project-sidebar" onClick={event => { const anchor = event.target.closest('a[href^="#"]'); if (anchor) { event.preventDefault(); document.getElementById(anchor.hash.slice(1))?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); } }}><p className="dev-eyebrow">IN THIS PROJECT</p><a href="#project-overview">Overview</a>{(project?.sections || []).map(([heading],i)=><a key={heading} href={`#section-${i}`}>{heading}</a>)}<a href="#project-connections">Connections</a><div className="project-tech"><p className="dev-eyebrow">TOOLS & TECHNOLOGIES</p>{(project?.stack || node.tags).map(tag=><span key={tag}>{tag}</span>)}</div></aside><div className="project-copy"><section id="project-overview"><h3>Overview</h3><p className="project-lead">{project?.intro || node.body}</p></section>{(project?.sections || [['In practice',node.facts.join(' ')]]).map(([heading,body],i)=><section id={`section-${i}`} key={heading}><span className="section-counter">0{i+1}</span><h3>{heading}</h3><p>{body}</p></section>)}{project?.resources && <section><h3>Related publications</h3>{project.resources.map(([label,url])=><a className="resource-link" key={url} href={url} target="_blank" rel="noopener noreferrer">{label} ↗</a>)}</section>}</div></div>
    <section id="project-connections" className="project-connections"><p className="dev-eyebrow">KEEP EXPLORING</p><h3>The connections behind the work.</h3><div>{related.map(n=><button key={n.id} onClick={()=>change(n.id)}><span><small>{n.relation}</small><strong>{n.title}</strong></span><span>↗</span></button>)}</div><button className="dev-secondary" onClick={scrollToExplorer}>↑ Back to the explorer</button></section></article>}</section>
    <section id="background" className="dev-background"><div className="background-heading"><p className="dev-eyebrow">02 / BEYOND THE PROJECTS</p><h2>A builder.<br />Always learning.</h2><p>{profile.personal}</p><p>{profile.education}</p><div className="language-note">Turkish <span>Native</span> · English <span>C1</span><br />German <span>A2–B1 · actively improving</span></div></div><div className="background-record"><h3>Technical toolkit</h3>{skills.map(([label,value])=><div className="skill-row" key={label}><h4>{label}</h4><p>{value}</p></div>)}<h3 className="cert-title">Certifications</h3>{certifications.map(([date,issuer,title])=><div className="cert-row" key={date}><span>{date}</span><p><strong>{issuer}</strong>{title}</p></div>)}</div></section><section className="dev-contact"><div><p className="dev-eyebrow">03 / LET’S CONNECT</p><h2>Have something in mind?</h2><p>A backend challenge, a product idea, or a conversation about the work.</p></div><a className="dev-primary" href={links.email}>dogukan.demir991@gmail.com ↗</a></section></main><footer className="dev-footer"><span>© {new Date().getFullYear()} Dogukan Demir</span><span>Software. Systems. Curiosity.</span><div><a href={links.github}>GitHub ↗</a><a href={links.linkedin}>LinkedIn ↗</a></div></footer></div>;
}


