// The route on the homepage, in chronological order. `node` opens that graph node's story.
export const route = [
  { year: '2019', label: 'B.Sc.', place: 'Düzce, Türkiye', category: 'education', node: 'duzce',
    title: 'Computer Engineering at Düzce University',
    text: 'I started a bachelor’s in Computer Engineering with a game already in progress. The degree taught me how software works; the game kept asking me to prove it.' },
  { year: '2019–23', label: 'Dead Inside', place: 'Solo project', category: 'games', node: 'dead-inside',
    title: 'Four years, one developer, one horror game',
    text: 'A first-person horror game, built alone alongside my studies and released on Steam in March 2023 — the project that taught me finishing is a skill of its own.' },
  { year: '2022', label: 'NTT DATA', place: 'Istanbul, Türkiye', category: 'experience', node: 'ntt',
    title: 'Industry, before graduation',
    text: 'In my final months at university I joined NTT DATA: a multi-tenant CRM of 50+ services, where one business process can fail halfway through five of them.' },
  { year: '2023', label: 'M.Sc.', place: 'Kaiserslautern, Germany', category: 'education', node: 'rptu',
    title: 'A master’s in Germany',
    text: 'Three months after my bachelor’s, I started an M.Sc. in Computer Science at RPTU Kaiserslautern-Landau, with a minor in Data Visualization.' },
  { year: '2024/25', label: 'Capstone', place: 'Fraunhofer IESE × John Deere', category: 'games', node: 'agriculture',
    title: 'Building a field before driving on one',
    text: 'For my capstone, a simulation environment for autonomous farm machinery. I was the architect, a developer and the project manager, in two-week sprints.' },
  { year: '2025', label: 'DFKI', place: 'Saarbrücken, Germany', category: 'research', node: 'dfki',
    title: 'Research engineering at DFKI',
    text: 'At the German Research Center for AI: an open-source gaze toolkit for XR, three VR training scenarios for manufacturing, and a study with 20 participants.' },
  { year: '2026', label: 'Erasmus+', place: 'Barcelona, Spain', category: 'education', node: 'uab',
    title: 'A semester at UAB Barcelona',
    text: 'Six months at Universitat Autònoma de Barcelona, studying Cloud Computing and Smart Industry — the infrastructure under software, and the industry around it.' },
  { year: '2026', label: 'Campus Games', place: 'Kaiserslautern & Landau', category: 'backend', node: 'campus',
    title: 'Rebuilding a platform for 1,000+ students',
    text: 'I rewrote a legacy university platform in Go. Registration went from 700 ms to 150 ms, and the timeouts at peak onboarding stopped.' },
  { year: '2026', label: 'RUSH', place: 'Remote, Germany', category: 'backend', node: 'rush',
    title: 'Leading software for autonomous drink kiosks',
    text: 'One Go backend behind the kiosk, the admin and machine control panels, payments and an AI voice — and now a TÜBİTAK 1507-funded service for predictive maintenance across the fleet.' },
  { year: 'Next', label: 'Next', place: 'Industry', category: 'next', node: null,
    title: 'A full-time engineering role',
    text: 'After the M.Sc., I want to build where software meets real systems: backends, cloud, and the hardware at the edge. If that’s what your team is building, let’s talk.' },
];
