// Expanded from the supplied CV. Keep outcomes distinct from responsibilities.
export const profile = {
  intro: 'I’m Dogukan, a software engineer who builds the systems behind the experience.',
  summary: 'My focus is backend engineering: Go and C#/.NET, distributed services, and cloud-native applications. Over 4+ years, I’ve worked across enterprise software, applied XR research, and early-stage products—taking systems from architecture to production.',
  personal: 'Games sparked my curiosity about software. Shipping my own game taught me to connect individual systems into a complete experience. Today, that same curiosity takes me from hardware-connected backends to interactive research environments.',
  education: 'Alongside my work, I’m completing an M.Sc. in Computer Science at RPTU Kaiserslautern-Landau, with a minor in Data Visualization. My Erasmus+ semester at Universitat Autònoma de Barcelona included Cloud Computing and Smart Industry.',
};
export const skills = [
  ['Languages', 'Go · C# · Python · TypeScript · JavaScript · SQL'],
  ['Backend', '.NET / ASP.NET Core · Entity Framework Core · Go net/http · Node.js · REST · Microservices · RabbitMQ · MQTT'],
  ['Cloud & delivery', 'AWS · Azure · Docker · Kubernetes · GitHub Actions · CI/CD · nginx · Cloudflare · Linux'],
  ['Data', 'PostgreSQL · MySQL · MongoDB · Redis · Cosmos DB · DynamoDB · Elasticsearch · TimescaleDB · Grafana'],
  ['AI & interaction', 'AWS Bedrock · Whisper · Piper · Unity · Unreal Engine · React · React Native'],
];
export const certifications = [
  ['2025', 'AWS Academy', 'Machine Learning for NLP · Machine Learning Foundations'],
  ['2024', 'Microsoft', 'Azure Cosmos DB Developer Specialty · DP-420'],
  ['2023', 'Microsoft', 'Azure Fundamentals · AZ-900'],
  ['2022', 'Microsoft', 'Azure AI Fundamentals · AI-900 / Azure Data Fundamentals · DP-900'],
];
export const details = {
  rush: { subtitle: 'Connecting applications, voice AI, and physical hardware.', period: 'Feb 2026 — Present', role: 'Software Team Lead · Part-time', place: 'Remote, Germany', intro: 'At Rush Automated Systems, I architected a Go backend from the ground up for three connected applications: a customer kiosk, an administration panel, and a content management system. The work spans API design, physical hardware integration, voice interaction, and production infrastructure.', metrics: [['3', 'Frontend applications'], ['Edge + cloud', 'Hybrid voice architecture'], ['Go', 'Core backend']], sections: [
    ['Architecture & application backend', 'I designed the REST API, data model, and service boundaries to support the three applications. The backend also communicates with dispensing hardware over MQTT and uses NFC-based customer authentication for returning users.'],
    ['Choosing where the computation runs', 'After benchmarking a fully cloud-based voice pipeline, I designed a hybrid approach. Speech-to-text and text-to-speech run locally on a Raspberry Pi 5, while AWS Bedrock handles LLM inference. This reduced end-to-end response latency and per-request cost without requiring all inference to run on the device.'],
    ['Deployment & delivery', 'The stack runs on AWS EC2 with Docker Compose. I configured nginx subdomain routing and Cloudflare TLS termination, and automated builds and releases through GitHub Actions. My role connects application architecture to the operational work needed to deliver it.'],
  ], stack: ['Go', 'REST APIs', 'MQTT', 'NFC', 'Raspberry Pi 5', 'AWS Bedrock', 'AWS EC2', 'Docker Compose', 'nginx', 'Cloudflare', 'GitHub Actions'] },
  campus: { subtitle: 'Rebuilding a university platform for two campuses.', period: 'Jan 2026 — Present', role: 'Backend Developer', place: 'Kaiserslautern, Germany', intro: 'RPTU Campus Games serves more than 1,000 students across Kaiserslautern and Landau. I re-engineered the legacy application and rewrote the backend in Go, with responsibility for both the application architecture and its operation in production.', metrics: [['1,000+', 'Students served'], ['700 → 150 ms', 'Registration API'], ['2', 'University campuses']], sections: [
    ['Modernizing the foundation', 'I restructured the codebase and service architecture to improve maintainability, performance, and scalability. The core game backend uses Go, with MongoDB and MySQL persistence.'],
    ['Faster, more reliable onboarding', 'Refactoring the university SSO integration reduced registration API response time from 700 ms to 150 ms—approximately 79%—and eliminated request timeouts during peak onboarding. I also implemented Firebase-based OTP authentication for phone-based access.'],
    ['Owning the production system', 'Beyond feature development, I implemented announcement services and containerized the services with Docker. I own deployment, monitoring, debugging, and incident response, connecting the work of building the system to keeping it reliable for students.'],
  ], stack: ['Go', 'MongoDB', 'MySQL', 'Firebase OTP', 'SSO', 'Docker', 'Production monitoring'] },
  'master-xr': { subtitle: 'Reusable gaze interaction, research tooling, and immersive training.', period: 'Jan 2025 — Jan 2026', role: 'Student Research Assistant', place: 'DFKI · Interactive Machine Learning · Saarbrücken', intro: 'At the German Research Center for Artificial Intelligence, I worked on the open-source Gaze Interaction Toolkit and the EU-funded MASTER XR project. My contribution brought together reusable framework engineering, Unity scene development, and data collection for interaction research.', metrics: [['3', 'VR training scenarios'], ['Open source', 'Gaze Interaction Toolkit'], ['Unity / C#', 'Interaction framework']], sections: [
    ['A framework for gaze and multimodal interaction', 'I co-developed GTK, a modular Unity framework that extends the XR Interaction Toolkit with gaze-based interaction and passive attention monitoring. I implemented reusable components for gaze selection, draggable objects, and hybrid gaze/controller interaction.'],
    ['Refactoring for reuse', 'I refactored the toolkit’s dependency modules and codebase, restructuring classes and separating responsibilities. The focus was modularity, maintainability, and making the framework easier to extend across different XR applications.'],
    ['Training environments & study tooling', 'For MASTER XR, I developed three VR manufacturing-training scenarios, including direct robot control and gaze-enhanced human–robot interaction. I also built study environments and automated pipelines to capture and process interaction telemetry, replacing manual logging and streamlining analysis.'],
    ['User studies & research collaboration', 'I conducted a user study with 20 participants in an industrial sorting scenario, with guided onboarding. The interaction data supported evaluation of toolkit usability and refinement of the study protocol. The toolkit was subsequently presented at IEEE VRW 2026. My role was research engineering and scene development; I am not a listed author of the linked publications.'],
  ], stack: ['Unity', 'C#', 'XR Interaction Toolkit', 'Gaze interaction', 'Telemetry', 'MASTER XR'], resources: [ ['GTK: An Open-Source Toolkit for Gaze-based Interaction in XR', 'https://www.dfki.de/en/web/research/projects-and-publications/publication/17190'], ['GTK: A Gaze-Based Interaction Toolkit in XR', 'https://www.dfki.de/en/web/research/projects-and-publications/publication/17191'] ] },
  ntt: { subtitle: 'Distributed enterprise systems, from business workflows to production.', period: 'Sep 2022 — Jan 2025', role: 'Software Engineer', place: 'Istanbul, Türkiye', intro: 'At NTT DATA, I contributed to a multi-tenant enterprise CRM platform and delivered mobile commerce applications. The work covered backend design, cloud migration, distributed workflows, integrations, and the day-to-day engineering needed to operate production services.', metrics: [['50+', 'Services contributed to'], ['12', 'Authorization tiers'], ['3', 'Production mobile apps']], sections: [
    ['Enterprise backend engineering', 'Using C#/.NET, I designed REST APIs, service boundaries, business workflows, and inter-service communication. The platform supported two enterprise tenants and 12 role-based authorization tiers, requiring tenant-aware business logic and consistent authentication and authorization flows.'],
    ['Coordinating distributed workflows', 'I implemented Saga and Event Sourcing workflows for long-running business transactions across independently deployed microservices. Redis caching and asynchronous messaging reduced synchronous dependencies and improved performance and resilience under load.'],
    ['Moving to the cloud', 'I helped move the platform from traditional infrastructure toward Azure, Azure Cosmos DB, Docker, and CI/CD. My work included deployment, monitoring, debugging, and production incident resolution alongside backend, DevOps, QA, and client teams.'],
    ['Conversational services & mobile delivery', 'I implemented a production chatbot service for Mercedes-Benz and integrated it into the enterprise service ecosystem. I also delivered three React Native and TypeScript e-commerce applications for the Kuwait market, integrating five payment providers, SAP SDKs, Google and Apple Maps, location-based filtering, and SSO.'],
  ], stack: ['C# / .NET', 'Azure', 'Cosmos DB', 'Saga', 'Event Sourcing', 'Redis', 'Docker', 'React Native', 'TypeScript'] },
  'dead-inside': { subtitle: 'From a personal idea to a commercial game on Steam.', period: 'Jan 2019 — Mar 2023', role: 'Solo developer', place: 'Independent project', intro: 'Dead Inside is a commercial first-person horror game that I developed and released on Steam. As its solo developer, I brought the gameplay systems together into a complete, playable experience—a project that sits at the beginning of my interest in software engineering.', metrics: [['Solo', 'Development'], ['Steam', 'Commercial release'], ['Unity / C#', 'Game engine & language']], sections: [
    ['Enemy behavior', 'I implemented a state-machine-driven enemy AI system. Explicit states and transitions provided a structured way to coordinate enemy behavior with the player’s actions and the rest of the gameplay.'],
    ['Gameplay systems', 'The game includes a weapon and inventory control system, together with kinematic animation blending. My work connected these individual mechanics so they functioned as parts of the same first-person experience.'],
    ['Taking a project to release', 'Shipping the game meant carrying an idea through implementation and into a commercial release. It gave me hands-on experience with the integration work behind an interactive product, and with taking responsibility for the complete result.'],
  ], stack: ['Unity', 'C#', 'State-machine AI', 'Animation blending', 'Inventory systems', 'Steam'] },
  agriculture: { subtitle: 'A simulation environment for autonomous agricultural machinery.', period: 'Sep 2024 — Jan 2025', role: 'Software architect · Developer · Project manager', place: 'M.Sc. capstone · Fraunhofer IESE & John Deere collaboration', intro: 'For my master’s capstone, I built a simulation environment for autonomous agricultural machinery in collaboration with Fraunhofer IESE and John Deere. The project combined simulation engineering with software architecture and team delivery.', metrics: [['CARLA', 'Simulation environment'], ['2 weeks', 'Agile sprint cycle'], ['M.Sc.', 'Capstone project']], sections: [
    ['Building the simulator', 'The environment used CARLA, Unreal Engine, Python, and Pygame. My responsibilities covered the software architecture and implementation of the simulation environment for autonomous agricultural machinery.'],
    ['Connecting design and delivery', 'Alongside development, I acted as project manager across two-week agile sprints. This put technical design and delivery planning in the same workflow, connecting implementation decisions with the team’s iteration cycle.'],
  ], stack: ['CARLA', 'Unreal Engine', 'Python', 'Pygame', 'Agile / Scrum'] },
  rptu: { subtitle: 'Computer science, visualization, and learning across disciplines.', period: 'Apr 2023 — Present', role: 'M.Sc. Computer Science', place: 'RPTU Kaiserslautern-Landau', intro: 'I’m completing a master’s in Computer Science at RPTU, with a minor in Data Visualization. My studies complement my professional backend work with opportunities to explore simulation, cloud computing, and interactive systems.', metrics: [['Computer Science', 'Master’s program'], ['Data Visualization', 'Minor'], ['Barcelona', 'Erasmus+ exchange']], sections: [
    ['International study', 'From January to July 2026, I studied at Universitat Autònoma de Barcelona through Erasmus+. My coursework included Cloud Computing and Smart Industry.'],
    ['Applied project work', 'My master’s capstone involved building an autonomous farming simulation environment in collaboration with Fraunhofer IESE and John Deere, using CARLA, Unreal Engine, Python, and Pygame.'],
    ['The foundation', 'Before RPTU, I completed a B.Sc. in Computer Engineering at Düzce University, from September 2019 to January 2023. I speak Turkish natively, English at C1 level, and German at an intermediate A2–B1 level, which I’m actively improving.'],
  ], stack: ['Computer Science', 'Data Visualization', 'Cloud Computing', 'Smart Industry'] },
};
